use super::*;

pub(super) fn compat_deps() -> compat_cmd::CompatDeps {
    compat_cmd::CompatDeps {
        print_help,
        print_task_help,
        print_version: compat_print_version,
        cmd_doctor: compat_cmd_doctor,
        cmd_where: compat_cmd_where,
        cmd_routes,
        cmd_diag: compat_cmd_diag,
        cmd_parity,
        cmd_core: compat_cmd_core,
        cmd_logs: compat_cmd_logs,
        cmd_task,
        print_metrics,
        print_profile,
        print_trace,
        print_alert,
        parse_optimize_args,
        print_optimize,
        print_worklog,
        cmd_cx,
        cmd_cxj,
        cmd_cxo,
        cmd_cxol,
        cmd_cxcopy,
        cmd_policy: compat_cmd_policy,
        cmd_state_show,
        cmd_state_get,
        cmd_state_set,
        cmd_llm: compat_cmd_llm,
        cmd_bench,
        cmd_prompt,
        cmd_roles,
        cmd_fanout,
        cmd_promptlint,
        cmd_next,
        cmd_fix,
        cmd_diffsum,
        cmd_commitjson,
        cmd_commitmsg,
        cmd_budget,
        cmd_log_tail,
        cmd_health: compat_cmd_health,
        cmd_rtk_status,
        cmd_log_on,
        cmd_log_off,
        cmd_alert_show,
        cmd_alert_on,
        cmd_alert_off,
        cmd_chunk,
        cmd_fix_run,
        cmd_replay,
        cmd_quarantine_list,
        cmd_quarantine_show,
    }
}

pub(super) fn native_deps() -> native_cmd::NativeDeps {
    native_cmd::NativeDeps {
        print_help,
        print_task_help,
        print_version: native_print_version,
        cmd_schema: native_cmd_schema,
        cmd_logs: native_cmd_logs,
        cmd_ci: native_cmd_ci,
        cmd_core: native_cmd_core,
        cmd_task,
        cmd_where: native_cmd_where,
        cmd_routes,
        cmd_diag: native_cmd_diag,
        cmd_parity,
        is_native_name,
        is_compat_name,
        cmd_doctor: native_cmd_doctor,
        cmd_state_show,
        cmd_state_get,
        cmd_state_set,
        cmd_llm: native_cmd_llm,
        cmd_policy: native_cmd_policy,
        cmd_bench,
        print_metrics,
        cmd_prompt,
        cmd_roles,
        cmd_fanout,
        cmd_promptlint,
        cmd_cx_compat,
        cmd_cx,
        cmd_cxj,
        cmd_cxo,
        cmd_cxol,
        cmd_cxcopy,
        cmd_fix,
        cmd_budget,
        cmd_log_tail,
        cmd_health: native_cmd_health,
        cmd_rtk_status,
        cmd_log_on,
        cmd_log_off,
        cmd_alert_show,
        cmd_alert_on,
        cmd_alert_off,
        cmd_chunk,
        print_profile,
        print_alert,
        parse_optimize_args,
        print_optimize,
        print_worklog,
        print_trace,
        cmd_next,
        cmd_diffsum,
        cmd_fix_run,
        cmd_commitjson,
        cmd_commitmsg,
        cmd_replay,
        cmd_quarantine_list,
        cmd_quarantine_show,
    }
}
