name: Bug Report
description: Report a reproducible defect in cx/cxrs behavior.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Clear description of the defect.
      placeholder: What broke and where?
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Reproduction Steps
      description: Exact commands and inputs to reproduce.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: What should happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      placeholder: What happened instead?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Include dependency versions.
      placeholder: |
        OS:
        bash:
        git:
        jq:
        codex:
        ollama (if used):
        rtk (if used):
        rustc/cargo:
    validations:
      required: true
