name: Contributor Task Proposal
description: Suggest a scoped contribution task with implementation plan.
title: "[Task]: "
labels: ["good first issue"]
body:
  - type: textarea
    id: task
    attributes:
      label: Task Description
      description: Single-scoped task proposal.
    validations:
      required: true

  - type: input
    id: area
    attributes:
      label: Target Area
      description: Module/file path.
      placeholder: rust/cxrs/src/modules/...
    validations:
      required: true

  - type: textarea
    id: test_plan
    attributes:
      label: Test Plan
      description: How the change should be validated.
    validations:
      required: true

  - type: textarea
    id: risks
    attributes:
      label: Risks / Contract Impact
      description: Potential impact on schemas, logs, pipelines, or safety policy.
    validations:
      required: true
